var dataSourceMock = [
  {"Row ID":1,"Order ID":3,"Order Date":"2010-10-13","Order Priority":"Low","Order Quantity":6,"Sales":261.54,"Discount":0.04,"Ship Mode":"Regular Air","Profit":-213.25,"Unit Price":38.94,"Shipping Cost":35,"Customer Name":"Muhammed MacIntyre","Province":"Nunavut","Region":"Nunavut","Customer Segment":"Small Business","Product Category":"Office Supplies","Product Sub-Category":"Storage & Organization","Product Name":"Eldon Base for stackable storage shelf, platinum","Product Container":"Large Box","Product Base Margin":0.8,"Ship Date":"2010-10-20"},
  {"Row ID":49,"Order ID":293,"Order Date":"2012-10-01","Order Priority":"High","Order Quantity":49,"Sales":10123.02,"Discount":0.07,"Ship Mode":"Delivery Truck","Profit":457.81,"Unit Price":208.16,"Shipping Cost":68.02,"Customer Name":"Barry French","Province":"Nunavut","Region":"Nunavut","Customer Segment":"Consumer","Product Category":"Office Supplies","Product Sub-Category":"Appliances","Product Name":"1.7 Cubic Foot Compact ","Product Container":"Jumbo Drum","Product Base Margin":0.58,"Ship Date":"2012-10-02"},
  {"Row ID":50,"Order ID":293,"Order Date":"2012-10-01","Order Priority":"High","Order Quantity":27,"Sales":244.57,"Discount":0.01,"Ship Mode":"Regular Air","Profit":46.71,"Unit Price":8.69,"Shipping Cost":2.99,"Customer Name":"Barry French","Province":"Nunavut","Region":"Nunavut","Customer Segment":"Consumer","Product Category":"Office Supplies","Product Sub-Category":"Binders and Binder Accessories","Product Name":"Cardinal Slant-D® Ring Binder, Heavy Gauge Vinyl","Product Container":"Small Box","Product Base Margin":0.39,"Ship Date":"2012-10-03"},
  {"Row ID":80,"Order ID":483,"Order Date":"2011-07-10","Order Priority":"High","Order Quantity":30,"Sales":4965.7595,"Discount":0.08,"Ship Mode":"Regular Air","Profit":1198.97,"Unit Price":195.99,"Shipping Cost":3.99,"Customer Name":"Clay Rozendal","Province":"Nunavut","Region":"Nunavut","Customer Segment":"Corporate","Product Category":"Technology","Product Sub-Category":"Telephones and Communication","Product Name":"R380","Product Container":"Small Box","Product Base Margin":0.58,"Ship Date":"2011-07-12"},
  {"Row ID":85,"Order ID":515,"Order Date":"2010-08-28","Order Priority":"Not Specified","Order Quantity":19,"Sales":394.27,"Discount":0.08,"Ship Mode":"Regular Air","Profit":30.94,"Unit Price":21.78,"Shipping Cost":5.94,"Customer Name":"Carlos Soltero","Province":"Nunavut","Region":"Nunavut","Customer Segment":"Consumer","Product Category":"Office Supplies","Product Sub-Category":"Appliances","Product Name":"Holmes HEPA Air Purifier","Product Container":"Medium Box","Product Base Margin":0.5,"Ship Date":"2010-08-30"},
  {"Row ID":86,"Order ID":515,"Order Date":"2010-08-28","Order Priority":"Not Specified","Order Quantity":21,"Sales":146.69,"Discount":0.05,"Ship Mode":"Regular Air","Profit":4.43,"Unit Price":6.64,"Shipping Cost":4.95,"Customer Name":"Carlos Soltero","Province":"Nunavut","Region":"Nunavut","Customer Segment":"Consumer","Product Category":"Furniture","Product Sub-Category":"Office Furnishings","Product Name":"G.E. Longer-Life Indoor Recessed Floodlight Bulbs","Product Container":"Small Pack","Product Base Margin":0.37,"Ship Date":"2010-08-30"},
  {"Row ID":97,"Order ID":613,"Order Date":"2011-06-17","Order Priority":"High","Order Quantity":12,"Sales":93.54,"Discount":0.03,"Ship Mode":"Regular Air","Profit":-54.04,"Unit Price":7.3,"Shipping Cost":7.72,"Customer Name":"Carl Jackson","Province":"Nunavut","Region":"Nunavut","Customer Segment":"Corporate","Product Category":"Office Supplies","Product Sub-Category":"Binders and Binder Accessories","Product Name":"Angle-D Binders with Locking Rings, Label Holders","Product Container":"Small Box","Product Base Margin":0.38,"Ship Date":"2011-06-17"},
  {"Row ID":98,"Order ID":613,"Order Date":"2011-06-17","Order Priority":"High","Order Quantity":22,"Sales":905.08,"Discount":0.09,"Ship Mode":"Regular Air","Profit":127.70,"Unit Price":42.76,"Shipping Cost":6.22,"Customer Name":"Carl Jackson","Province":"Nunavut","Region":"Nunavut","Customer Segment":"Corporate","Product Category":"Office Supplies","Product Sub-Category":"Storage & Organization","Product Name":"SAFCO Mobile Desk Side File, Wire Frame","Product Container":"Small Box","Product Base Margin":null,"Ship Date":"2011-06-18"},
  {"Row ID":103,"Order ID":643,"Order Date":"2011-03-24","Order Priority":"High","Order Quantity":21,"Sales":2781.82,"Discount":0.07,"Ship Mode":"Express Air","Profit":-695.26,"Unit Price":138.14,"Shipping Cost":35,"Customer Name":"Monica Federle","Province":"Nunavut","Region":"Nunavut","Customer Segment":"Corporate","Product Category":"Office Supplies","Product Sub-Category":"Storage & Organization","Product Name":"SAFCO Commercial Wire Shelving, Black","Product Container":"Large Box","Product Base Margin":null,"Ship Date":"2011-03-25"},
  {"Row ID":107,"Order ID":678,"Order Date":"2010-02-26","Order Priority":"Low","Order Quantity":44,"Sales":228.41,"Discount":0.07,"Ship Mode":"Regular Air","Profit":-226.36,"Unit Price":4.98,"Shipping Cost":8.33,"Customer Name":"Dorothy Badders","Province":"Nunavut","Region":"Nunavut","Customer Segment":"Home Office","Product Category":"Office Supplies","Product Sub-Category":"Paper","Product Name":"Xerox 198","Product Container":"Small Box","Product Base Margin":0.38,"Ship Date":"2010-02-26"}
];

module.exports = dataSourceMock;